FROM gettyimages/spark

RUN curl -O ftp://ita.ee.lbl.gov/traces/NASA_access_log_Jul95.gz
RUN gzip -d NASA_access_log_Jul95.gz
RUN mv NASA_access_log_Jul95 /root/
RUN apt-get update && apt-get install -y ssh  openssh-server  software-properties-common
#RUN apt-get install -y  openjdk-8-jre-headless ca-certificates-javaß

RUN ssh-keygen -t rsa -f ~/.ssh/id_rsa -P '' && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
RUN echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
RUN apt-get update
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
RUN apt-get install -y oracle-java8-installer

RUN echo  "export JAVA_HOME=/usr/jdk1.8.0_131" >>  $HADOOP_CONF_DIR/hadoop-env.sh
RUN echo  "export JAVA_HOME=/usr/jdk1.8.0_131" >>  $SPARK_HOME/sbin/spark-config.sh
RUN echo "export SPARK_DAEMON_CLASSPATH=$(hadoop classpath)" >> $SPARK_HOME/conf/spark-env.sh
RUN echo "export SPARK_CLASSPATH=$(hadoop classpath)" >> $SPARK_HOME/conf/spark-env.sh
RUN echo "export SPARK_DIST_CLASSPATH=$(hadoop classpath)" >> $SPARK_HOME/conf/spark-env.sh
RUN echo "export HADOOP_CONF_DIR=$HADOOP_CONF_DIR" >> $SPARK_HOME/conf/spark-env.sh

RUN echo  "export JAVA_HOME=/usr/jdk1.8.0_131" >> /root/.bashrc
RUN echo "3" > /root/some_logs

COPY tasks.py /root/
COPY core-site.xml $HADOOP_HOME/etc/hadoop/
COPY yarn-site.xml $HADOOP_HOME/etc/hadoop/
COPY hdfs-site.xml $HADOOP_HOME/etc/hadoop/
COPY slaves $SPARK_HOME/conf/

COPY run.sh /root/
RUN chmod u+x /root/run.sh

COPY ssh_config /root/.ssh/config

CMD /etc/init.d/ssh start && tail -f /root/some_logs
